---

- name: Getting wiremock jar
  get_url:
    url: "{{ wiremock_src }}"
    dest: "{{ wiremock_original }}"
  notify: restart wiremock
  become: yes

- name: Linking wiremock jar
  file:
    src: "{{ wiremock_original }}"
    dest: "{{ wiremock_dest }}"
    state: link
  become: yes
